    dict(
        id=377,
        kode='ar-payment-sts-item',
        nama=' STS Item',
        path='/ar/payment/sts',
        perm_name='read',
        ),
    dict(
        id=378,
        kode='ar-payment-sts-item-add',
        nama='Tambah STS Item',
        path='/ar/payment/sts/add',
        perm_name='read',
        ),
    dict(
        id=379,
        kode='ar-payment-sts-item-edit',
        nama='Edit STS Item',
        path='/ar/payment/sts/{id}/edit',
        perm_name='edit',
        ),
    dict(
        id=380,
        kode='ar-payment-sts-item-delete',
        nama='Hapus STS Item',
        path='/ar/payment/sts/{id}/delete',
        perm_name='delete',
        ),
    dict(
        id=381,
        kode='ar-payment-sts-item-act',
        nama=' STS Item Act',
        path='/ar/payment/sts/{act}/act',
        perm_name='read',
        ),
